name: Deprecate Notebook

on:
  workflow_call:
    inputs:
      notebook-path:
        description: "Path to the notebook to deprecate (e.g., notebooks/MIRI/JWPipeNB-MIRI-MRS.ipynb)"
        required: true
        type: string
    secrets:
      github-token:
        required: true

jobs:
  deprecate-notebook:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Add Deprecation Banner and Metadata
        run: |
          NOTEBOOK="${{ inputs.notebook-path }}"

          echo "Deprecating notebook: $NOTEBOOK"

          if [[ ! -f "$NOTEBOOK" ]]; then
            echo "ERROR: Notebook not found at $NOTEBOOK"
            exit 1
          fi

          # Calculate removal date 30 days from today
          REMOVAL_DATE=$(date -u -d "+30 days" +"%Y-%m-%d")

          echo "Setting removal date to: $REMOVAL_DATE"

          # Insert a Markdown warning cell at the top
          jq --arg date "$REMOVAL_DATE" \
            '.cells |= [{"cell_type":"markdown","metadata":{},"source":["⚠️ **DEPRECATED**: This notebook is scheduled for removal on \($date).\n"]}] + .' \
            "$NOTEBOOK" > temp1.json && mv temp1.json "$NOTEBOOK"

          # Add deprecation metadata
          jq '.metadata.deprecated = {"status": true, "removal_date": "'"$REMOVAL_DATE"'"}' "$NOTEBOOK" > temp2.json && mv temp2.json "$NOTEBOOK"

      - name: Commit and Push Deprecation Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git checkout gh-storage || git checkout -b gh-storage
          git add "${{ inputs.notebook-path }}"
          git commit -m "Manually deprecated notebook ${{ inputs.notebook-path }} (removal in 30 days)"
          git push origin gh-storage
        env:
          GITHUB_TOKEN: ${{ secrets.github-token }}

